use input_linux::Key;

use crate::shortcut::{KeyCode, MouseButton};

/// Every key the application can emit. Device capabilities are derived from this list
/// so they can never drift from the `KeyCode` mapping below.
pub(super) const ALL_KEY_CODES: &[KeyCode] = &[
    KeyCode::Alt,
    KeyCode::AltLeft,
    KeyCode::AltRight,
    KeyCode::Space,
    KeyCode::Shift,
    KeyCode::ShiftLeft,
    KeyCode::ShiftRight,
    KeyCode::Control,
    KeyCode::ControlLeft,
    KeyCode::ControlRight,
    KeyCode::MetaLeft,
    KeyCode::MetaRight,
    KeyCode::Enter,
    KeyCode::Tab,
    KeyCode::Escape,
    KeyCode::Backspace,
    KeyCode::Delete,
    KeyCode::Insert,
    KeyCode::Home,
    KeyCode::End,
    KeyCode::PageUp,
    KeyCode::PageDown,
    KeyCode::ArrowUp,
    KeyCode::ArrowDown,
    KeyCode::ArrowLeft,
    KeyCode::ArrowRight,
    KeyCode::CapsLock,
    KeyCode::NumLock,
    KeyCode::ScrollLock,
    KeyCode::PrintScreen,
    KeyCode::Pause,
    KeyCode::ContextMenu,
    KeyCode::A,
    KeyCode::B,
    KeyCode::C,
    KeyCode::D,
    KeyCode::E,
    KeyCode::F,
    KeyCode::G,
    KeyCode::H,
    KeyCode::I,
    KeyCode::J,
    KeyCode::K,
    KeyCode::L,
    KeyCode::M,
    KeyCode::N,
    KeyCode::O,
    KeyCode::P,
    KeyCode::Q,
    KeyCode::R,
    KeyCode::S,
    KeyCode::T,
    KeyCode::U,
    KeyCode::V,
    KeyCode::W,
    KeyCode::X,
    KeyCode::Y,
    KeyCode::Z,
    KeyCode::Digit0,
    KeyCode::Digit1,
    KeyCode::Digit2,
    KeyCode::Digit3,
    KeyCode::Digit4,
    KeyCode::Digit5,
    KeyCode::Digit6,
    KeyCode::Digit7,
    KeyCode::Digit8,
    KeyCode::Digit9,
    KeyCode::BracketLeft,
    KeyCode::BracketRight,
    KeyCode::Backquote,
    KeyCode::Minus,
    KeyCode::Equal,
    KeyCode::Backslash,
    KeyCode::Semicolon,
    KeyCode::Quote,
    KeyCode::Comma,
    KeyCode::Period,
    KeyCode::Slash,
    KeyCode::F1,
    KeyCode::F2,
    KeyCode::F3,
    KeyCode::F4,
    KeyCode::F5,
    KeyCode::F6,
    KeyCode::F7,
    KeyCode::F8,
    KeyCode::F9,
    KeyCode::F10,
    KeyCode::F11,
    KeyCode::F12,
    KeyCode::F13,
    KeyCode::F14,
    KeyCode::F15,
    KeyCode::F16,
    KeyCode::F17,
    KeyCode::F18,
    KeyCode::F19,
    KeyCode::F20,
    KeyCode::F21,
    KeyCode::F22,
    KeyCode::F23,
    KeyCode::F24,
    KeyCode::Numpad0,
    KeyCode::Numpad1,
    KeyCode::Numpad2,
    KeyCode::Numpad3,
    KeyCode::Numpad4,
    KeyCode::Numpad5,
    KeyCode::Numpad6,
    KeyCode::Numpad7,
    KeyCode::Numpad8,
    KeyCode::Numpad9,
    KeyCode::NumpadAdd,
    KeyCode::NumpadSubtract,
    KeyCode::NumpadMultiply,
    KeyCode::NumpadDivide,
    KeyCode::NumpadDecimal,
    KeyCode::NumpadEnter,
    KeyCode::VolumeMute,
    KeyCode::VolumeDown,
    KeyCode::VolumeUp,
    KeyCode::MediaPreviousTrack,
    KeyCode::MediaNextTrack,
    KeyCode::MediaPlayPause,
    KeyCode::MediaStop,
    KeyCode::BrowserBack,
    KeyCode::BrowserForward,
    KeyCode::BrowserRefresh,
    KeyCode::BrowserStop,
    KeyCode::BrowserSearch,
    KeyCode::BrowserFavorites,
    KeyCode::BrowserHome,
];

/// Maps every application key onto its Linux `KEY_*` equivalent; the Linux input
/// headers define a code for all of them, including F13-F24 and the media keys.
pub(super) fn linux_key(key: KeyCode) -> Key {
    match key {
        KeyCode::Alt | KeyCode::AltLeft => Key::LeftAlt,
        KeyCode::AltRight => Key::RightAlt,
        KeyCode::Space => Key::Space,
        KeyCode::Shift | KeyCode::ShiftLeft => Key::LeftShift,
        KeyCode::ShiftRight => Key::RightShift,
        KeyCode::Control | KeyCode::ControlLeft => Key::LeftCtrl,
        KeyCode::ControlRight => Key::RightCtrl,
        KeyCode::MetaLeft => Key::LeftMeta,
        KeyCode::MetaRight => Key::RightMeta,
        KeyCode::Enter => Key::Enter,
        KeyCode::Tab => Key::Tab,
        KeyCode::Escape => Key::Esc,
        KeyCode::Backspace => Key::Backspace,
        KeyCode::Delete => Key::Delete,
        KeyCode::Insert => Key::Insert,
        KeyCode::Home => Key::Home,
        KeyCode::End => Key::End,
        KeyCode::PageUp => Key::PageUp,
        KeyCode::PageDown => Key::PageDown,
        KeyCode::ArrowUp => Key::Up,
        KeyCode::ArrowDown => Key::Down,
        KeyCode::ArrowLeft => Key::Left,
        KeyCode::ArrowRight => Key::Right,
        KeyCode::CapsLock => Key::CapsLock,
        KeyCode::NumLock => Key::NumLock,
        KeyCode::ScrollLock => Key::ScrollLock,
        KeyCode::PrintScreen => Key::Sysrq,
        KeyCode::Pause => Key::Pause,
        KeyCode::ContextMenu => Key::Menu,
        KeyCode::A => Key::A,
        KeyCode::B => Key::B,
        KeyCode::C => Key::C,
        KeyCode::D => Key::D,
        KeyCode::E => Key::E,
        KeyCode::F => Key::F,
        KeyCode::G => Key::G,
        KeyCode::H => Key::H,
        KeyCode::I => Key::I,
        KeyCode::J => Key::J,
        KeyCode::K => Key::K,
        KeyCode::L => Key::L,
        KeyCode::M => Key::M,
        KeyCode::N => Key::N,
        KeyCode::O => Key::O,
        KeyCode::P => Key::P,
        KeyCode::Q => Key::Q,
        KeyCode::R => Key::R,
        KeyCode::S => Key::S,
        KeyCode::T => Key::T,
        KeyCode::U => Key::U,
        KeyCode::V => Key::V,
        KeyCode::W => Key::W,
        KeyCode::X => Key::X,
        KeyCode::Y => Key::Y,
        KeyCode::Z => Key::Z,
        KeyCode::Digit0 => Key::Num0,
        KeyCode::Digit1 => Key::Num1,
        KeyCode::Digit2 => Key::Num2,
        KeyCode::Digit3 => Key::Num3,
        KeyCode::Digit4 => Key::Num4,
        KeyCode::Digit5 => Key::Num5,
        KeyCode::Digit6 => Key::Num6,
        KeyCode::Digit7 => Key::Num7,
        KeyCode::Digit8 => Key::Num8,
        KeyCode::Digit9 => Key::Num9,
        KeyCode::BracketLeft => Key::LeftBrace,
        KeyCode::BracketRight => Key::RightBrace,
        KeyCode::Backquote => Key::Grave,
        KeyCode::Minus => Key::Minus,
        KeyCode::Equal => Key::Equal,
        KeyCode::Backslash => Key::Backslash,
        KeyCode::Semicolon => Key::Semicolon,
        KeyCode::Quote => Key::Apostrophe,
        KeyCode::Comma => Key::Comma,
        KeyCode::Period => Key::Dot,
        KeyCode::Slash => Key::Slash,
        KeyCode::F1 => Key::F1,
        KeyCode::F2 => Key::F2,
        KeyCode::F3 => Key::F3,
        KeyCode::F4 => Key::F4,
        KeyCode::F5 => Key::F5,
        KeyCode::F6 => Key::F6,
        KeyCode::F7 => Key::F7,
        KeyCode::F8 => Key::F8,
        KeyCode::F9 => Key::F9,
        KeyCode::F10 => Key::F10,
        KeyCode::F11 => Key::F11,
        KeyCode::F12 => Key::F12,
        KeyCode::F13 => Key::F13,
        KeyCode::F14 => Key::F14,
        KeyCode::F15 => Key::F15,
        KeyCode::F16 => Key::F16,
        KeyCode::F17 => Key::F17,
        KeyCode::F18 => Key::F18,
        KeyCode::F19 => Key::F19,
        KeyCode::F20 => Key::F20,
        KeyCode::F21 => Key::F21,
        KeyCode::F22 => Key::F22,
        KeyCode::F23 => Key::F23,
        KeyCode::F24 => Key::F24,
        KeyCode::Numpad0 => Key::Kp0,
        KeyCode::Numpad1 => Key::Kp1,
        KeyCode::Numpad2 => Key::Kp2,
        KeyCode::Numpad3 => Key::Kp3,
        KeyCode::Numpad4 => Key::Kp4,
        KeyCode::Numpad5 => Key::Kp5,
        KeyCode::Numpad6 => Key::Kp6,
        KeyCode::Numpad7 => Key::Kp7,
        KeyCode::Numpad8 => Key::Kp8,
        KeyCode::Numpad9 => Key::Kp9,
        KeyCode::NumpadAdd => Key::KpPlus,
        KeyCode::NumpadSubtract => Key::KpMinus,
        KeyCode::NumpadMultiply => Key::KpAsterisk,
        KeyCode::NumpadDivide => Key::KpSlash,
        KeyCode::NumpadDecimal => Key::KpDot,
        KeyCode::NumpadEnter => Key::KpEnter,
        KeyCode::VolumeMute => Key::Mute,
        KeyCode::VolumeDown => Key::VolumeDown,
        KeyCode::VolumeUp => Key::VolumeUp,
        KeyCode::MediaPreviousTrack => Key::PreviousSong,
        KeyCode::MediaNextTrack => Key::NextSong,
        KeyCode::MediaPlayPause => Key::PlayPause,
        KeyCode::MediaStop => Key::StopCD,
        KeyCode::BrowserBack => Key::Back,
        KeyCode::BrowserForward => Key::Forward,
        KeyCode::BrowserRefresh => Key::Refresh,
        KeyCode::BrowserStop => Key::Stop,
        KeyCode::BrowserSearch => Key::Search,
        KeyCode::BrowserFavorites => Key::Bookmarks,
        KeyCode::BrowserHome => Key::Homepage,
    }
}

pub(super) fn button_key(button: MouseButton) -> Key {
    match button {
        MouseButton::Left => Key::ButtonLeft,
        MouseButton::Right => Key::ButtonRight,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn modifier_keys_map_to_linux_codes() {
        assert_eq!(linux_key(KeyCode::Control), Key::LeftCtrl);
        assert_eq!(linux_key(KeyCode::ControlRight), Key::RightCtrl);
        assert_eq!(linux_key(KeyCode::MetaLeft), Key::LeftMeta);
        assert_eq!(linux_key(KeyCode::AltRight), Key::RightAlt);
        assert_eq!(linux_key(KeyCode::Escape), Key::Esc);
        assert_eq!(linux_key(KeyCode::PrintScreen), Key::Sysrq);
        assert_eq!(linux_key(KeyCode::ContextMenu), Key::Menu);
        assert_eq!(linux_key(KeyCode::NumpadEnter), Key::KpEnter);
        assert_eq!(linux_key(KeyCode::MediaPlayPause), Key::PlayPause);
        assert_eq!(linux_key(KeyCode::BrowserHome), Key::Homepage);
        assert_eq!(linux_key(KeyCode::F24), Key::F24);
        assert_eq!(linux_key(KeyCode::Digit0), Key::Num0);
        assert_eq!(linux_key(KeyCode::BracketLeft), Key::LeftBrace);
        assert_eq!(linux_key(KeyCode::Quote), Key::Apostrophe);
    }
}
